# Generated by Django 5.2.11 on 2026-04-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurants', '0004_booking_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='menus',
            field=models.ManyToManyField(blank=True, to='menu.menu'),
        ),
    ]
