# Generated by Django 5.2.11 on 2026-03-31 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
